### ISSUE TITLE
Not an issue, just want to say thank you!

### ISSUE THREAD

**Issue by ms-jpq** [sej7278/virt-installs#1]
#thank

**Comment by sej7278** [comment]
:+1: thanks a lot, glad it helped someone, i was considering taking it down as nobody seemed to be using it

**Comment by ms-jpq** [comment]
nooo please dont take it down!
it really helps, saves me (and other people) alotta time trying to read through the gigantic manual

**Comment by sej7278** [comment]
i'm about to upload a suse12 template that uses autoyast (like kickstart) from the initrd or nfs, so will keep the repo around.
